# SEO settings
title: "Hanief Utama"
title_left: "hanief"
title_right: "utama"
description: "essays and projects"
keywords: "hanief, haniefutama, cahyautama, cahya, utama, blog, personal blog, software engineer, writer, essays, codes"
url: https://haniefutama.com
baseurl: null
cover: /public/logo_social.png

repo: https://github.com/hanief/haniefutama
disqus_shortname: "haniefutama"
twitter_username: "hnfutama"
comments: false

# Build settings
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name: "Hanief Utama"
  job: "writer"
  bio: "essays and projects"
  thumb: images/logo.png
  email: halo@haniefutama.com
  url: https://haniefutama.com
  github: https://github.com/hanief
  twitter: https://twitter.com/hnfutama
  facebook: https://www.facebook.com/haniefcutama
  instagram: https://www.instagram.com/haniefutama
  linkedin: https://linkedin.com/in/haniefutama

# social settings
og_locale: "id_ID"
twitter_card: "summary"
twitter_site: "@hnfutama"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
  - ".travis.yml"
  - ".gitignore"
  - ".DS_Store"
  - "LICENSE"
  - "haniefutama.code-workspace"
